module.exports = [
    {
        name: "China", 
        demonym: "Chinese", 
        capital: "Beijing", 
        largestCity: "Shanghai", 
        population: "1.434 billion",
        flagImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/250px-Flag_of_the_People%27s_Republic_of_China.svg.png", 
    }, 
    {
        name: "India", 
        demonym: "Indian", 
        capital: "New Delhi", 
        largestCity: "Mumbai", 
        population: "1.366 billion", 
        flagImg: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/250px-Flag_of_India.svg.png", 
    }, 
    {
        name: "United States of America", 
        demonym: "American", 
        capital: "Washington, D.C.", 
        largestCity: "New York City", 
        population: "332 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/250px-Flag_of_the_United_States.svg.png", 
    }, 
    {
        name: "Indonesia", 
        demonym: "Indonesian", 
        capital: "Jakarta", 
        largestCity: "Jakarta", 
        population: "271 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/250px-Flag_of_Indonesia.svg.png", 
    }, 
    {
        name: "Pakistan", 
        demonym: "Pakistani", 
        capital: "Islamabad", 
        largestCity: "Karachi", 
        population: "227 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/250px-Flag_of_Pakistan.svg.png", 
    }, 
    {
        name: "Brazil", 
        demonym: "Brazilian", 
        capital: "Brasilia", 
        largestCity: "Sao Paulo", 
        population: "211 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/250px-Flag_of_Brazil.svg.png", 
    }, 
    {
        name: "Nigeria", 
        demonym: "Nigerian", 
        capital: "Abuja", 
        largestCity: "Lagos", 
        population: "211 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/250px-Flag_of_Nigeria.svg.png", 
    }, 
    {
        name: "Bangladesh", 
        demonym: "Bangladeshi", 
        capital: "Dhaka", 
        largestCity: "Dhaka", 
        population: "163 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/250px-Flag_of_Bangladesh.svg.png", 
    }, 
    {
        name: "Russia", 
        demonym: "Russian", 
        capital: "Moscow", 
        largestCity: "Moscow", 
        population: "146 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/250px-Flag_of_Russia.svg.png", 
    }, 
    {
        name: "Mexico", 
        demonym: "Mexican", 
        capital: "Mexico City", 
        largestCity: "Mexico City", 
        population: "128 million", 
        flagImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/250px-Flag_of_Mexico.svg.png", 
    }, 
]