module.exports = [
    {
        name: "China", 
        demonym: "Chinese", 
        capital: "Beijing", 
        largestCity: "Shanghai", 
        population: "1.434 billion",
    }, 
    {
        name: "India", 
        demonym: "Indian", 
        capital: "New Delhi", 
        largestCity: "Mumbai", 
        population: "1.366 billion",
    }, 
    {
        name: "United States of America", 
        demonym: "American", 
        capital: "Washington, D.C.", 
        largestCity: "New York City", 
        population: "332 million",
    }, 
    {
        name: "Indonesia", 
        demonym: "Indonesian", 
        capital: "Jakarta", 
        largestCity: "Jakarta", 
        population: "271 million",
    }, 
    {
        name: "Pakistan", 
        demonym: "Pakistani", 
        capital: "Islamabad", 
        largestCity: "Karachi", 
        population: "227 million",
    }, 
    {
        name: "Brazil", 
        demonym: "Brazilian", 
        capital: "Brasilia", 
        largestCity: "Sao Paulo", 
        population: "211 million",
    }, 
    {
        name: "Nigeria", 
        demonym: "Nigerian", 
        capital: "Abuja", 
        largestCity: "Lagos", 
        population: "211 million",
    }, 
    {
        name: "Bangladesh", 
        demonym: "Bangladeshi", 
        capital: "Dhaka", 
        largestCity: "Dhaka", 
        population: "163 million",
    }, 
    {
        name: "Russia", 
        demonym: "Russian", 
        capital: "Moscow", 
        largestCity: "Moscow", 
        population: "146 million",
    }, 
    {
        name: "Mexico", 
        demonym: "Mexican", 
        capital: "Mexico City", 
        largestCity: "Mexico City", 
        population: "128 million",
    }, 
]